pub const MICHISUJI_TARGET_VERSION: &str = "7.22.2";
pub const RB2011_ARCHITECTURE: &str = "mipsbe";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MichisujiRackProfile {
    pub router_identity: String,
    pub server_address: String,
    pub public_service_port: u16,
    pub internal_service_port: u16,
    pub uplink_interface: String,
    pub lan_bridge: String,
    pub allowed_admin_subnet: String,
    pub fasttrack: bool,
    pub system_channel: String,
    pub expected_system_version: String,
    pub architecture: String,
}

impl MichisujiRackProfile {
    pub fn rb2011(server_address: impl Into<String>, public_service_port: u16) -> Self {
        Self {
            router_identity: "omoikane-michisuji-rb2011".to_string(),
            server_address: server_address.into(),
            public_service_port,
            internal_service_port: public_service_port,
            uplink_interface: "ether1".to_string(),
            lan_bridge: "bridge".to_string(),
            allowed_admin_subnet: "192.168.88.0/24".to_string(),
            fasttrack: true,
            system_channel: "stable".to_string(),
            expected_system_version: MICHISUJI_TARGET_VERSION.to_string(),
            architecture: RB2011_ARCHITECTURE.to_string(),
        }
    }

    pub fn with_identity(mut self, identity: impl Into<String>) -> Self {
        self.router_identity = identity.into();
        self
    }

    pub fn with_uplink_interface(mut self, interface: impl Into<String>) -> Self {
        self.uplink_interface = interface.into();
        self
    }

    pub fn with_lan_bridge(mut self, bridge: impl Into<String>) -> Self {
        self.lan_bridge = bridge.into();
        self
    }

    pub fn with_allowed_admin_subnet(mut self, subnet: impl Into<String>) -> Self {
        self.allowed_admin_subnet = subnet.into();
        self
    }

    pub fn with_internal_service_port(mut self, port: u16) -> Self {
        self.internal_service_port = port;
        self
    }

    pub fn without_fasttrack(mut self) -> Self {
        self.fasttrack = false;
        self
    }

    pub fn render_script(&self) -> Result<String, MichisujiScriptError> {
        self.validate()?;

        let identity = michisuji_quote(&self.router_identity);
        let channel = michisuji_quote(&self.system_channel);
        let uplink = michisuji_quote(&self.uplink_interface);
        let bridge = michisuji_quote(&self.lan_bridge);
        let server = michisuji_quote(&self.server_address);
        let admin_subnet = michisuji_quote(&self.allowed_admin_subnet);
        let expected = michisuji_quote(&self.expected_system_version);
        let architecture = michisuji_quote(&self.architecture);

        let mut script = String::new();
        script.push_str("# Omoikane Michisuji rack profile for RB2011\n");
        script.push_str("# Generated by omoikane_web. Review before applying in production.\n");
        script.push_str(&format!("# target-system-version={expected}\n"));
        script.push_str(&format!("# target-architecture={architecture}\n"));
        script.push_str(&format!("/system identity set name={identity}\n"));
        script.push_str(&format!("/system package update set channel={channel}\n"));
        script.push_str(
            "/ip firewall filter add chain=input action=accept connection-state=established,related comment=\"omoikane michisuji accept established input\"\n",
        );
        script.push_str(&format!(
            "/ip firewall filter add chain=input action=accept protocol=tcp dst-port={} src-address={} comment=\"omoikane michisuji admin ingress\"\n",
            self.public_service_port, admin_subnet
        ));
        script.push_str(
            "/ip firewall filter add chain=input action=drop connection-state=invalid comment=\"omoikane michisuji drop invalid input\"\n",
        );
        if self.fasttrack {
            script.push_str(
                "/ip firewall filter add chain=forward action=fasttrack-connection connection-state=established,related hw-offload=yes comment=\"omoikane michisuji rb2011 fasttrack\"\n",
            );
        }
        script.push_str(
            "/ip firewall filter add chain=forward action=accept connection-state=established,related comment=\"omoikane michisuji accept established forward\"\n",
        );
        script.push_str(&format!(
            "/ip firewall nat add chain=dstnat in-interface={} protocol=tcp dst-port={} action=dst-nat to-addresses={} to-ports={} comment=\"omoikane hayate status ingress\"\n",
            uplink, self.public_service_port, server, self.internal_service_port
        ));
        script.push_str(&format!(
            "/ip firewall nat add chain=srcnat out-interface={} action=masquerade comment=\"omoikane michisuji outbound masquerade\"\n",
            uplink
        ));
        script.push_str(&format!(
            "/interface bridge set [find name={}] protocol-mode=rstp comment=\"omoikane michisuji rack bridge\"\n",
            bridge
        ));
        script.push_str("/system routerboard settings set auto-upgrade=yes\n");
        Ok(script)
    }

    fn validate(&self) -> Result<(), MichisujiScriptError> {
        validate_non_empty("router_identity", &self.router_identity)?;
        validate_non_empty("server_address", &self.server_address)?;
        validate_non_empty("uplink_interface", &self.uplink_interface)?;
        validate_non_empty("lan_bridge", &self.lan_bridge)?;
        validate_non_empty("allowed_admin_subnet", &self.allowed_admin_subnet)?;
        validate_non_empty("system_channel", &self.system_channel)?;
        validate_non_empty("expected_system_version", &self.expected_system_version)?;
        validate_non_empty("architecture", &self.architecture)?;
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MichisujiScriptError {
    EmptyField(&'static str),
}

fn validate_non_empty(field: &'static str, value: &str) -> Result<(), MichisujiScriptError> {
    if value.trim().is_empty() {
        Err(MichisujiScriptError::EmptyField(field))
    } else {
        Ok(())
    }
}

fn michisuji_quote(value: &str) -> String {
    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('"');
    for ch in value.chars() {
        match ch {
            '"' | '\\' | '$' | '`' => {
                quoted.push('\\');
                quoted.push(ch);
            }
            '\n' | '\r' => quoted.push(' '),
            ch => quoted.push(ch),
        }
    }
    quoted.push('"');
    quoted
}

#[cfg(test)]
mod tests {
    use super::{
        MICHISUJI_TARGET_VERSION, MichisujiRackProfile, MichisujiScriptError, RB2011_ARCHITECTURE,
    };

    #[test]
    fn rb2011_profile_generates_michisuji_script() {
        let script = MichisujiRackProfile::rb2011("10.10.10.20", 8080)
            .with_identity("omoikane rack 01")
            .with_allowed_admin_subnet("10.10.10.0/24")
            .render_script()
            .expect("michisuji script");

        assert!(script.contains("# target-system-version=\"7.22.2\""));
        assert!(script.contains("# target-architecture=\"mipsbe\""));
        assert!(script.contains("/system identity set name=\"omoikane rack 01\""));
        assert!(script.contains("action=fasttrack-connection"));
        assert!(script.contains("to-addresses=\"10.10.10.20\""));
        assert!(script.contains("src-address=\"10.10.10.0/24\""));
    }

    #[test]
    fn rb2011_profile_can_disable_fasttrack_for_debugging() {
        let script = MichisujiRackProfile::rb2011("10.10.10.20", 8080)
            .without_fasttrack()
            .render_script()
            .expect("michisuji script");

        assert!(!script.contains("fasttrack-connection"));
        assert_eq!(MICHISUJI_TARGET_VERSION, "7.22.2");
        assert_eq!(RB2011_ARCHITECTURE, "mipsbe");
    }

    #[test]
    fn rb2011_profile_rejects_empty_fields() {
        let err = MichisujiRackProfile::rb2011("", 8080)
            .render_script()
            .unwrap_err();
        assert_eq!(err, MichisujiScriptError::EmptyField("server_address"));
    }
}
