[package]
name = "omoikane_web"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
actix-web = { version = "4.13.0", default-features = false }
daikoku = { path = "../daikoku", version = "0.1.0" }
omoikane_control = { path = "../omoikane_control", version = "0.1.0" }
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "postgres"] }

[lib]
path = "src/lib.rs"
