[package]
name = "shinobi"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
sekai = { path = "../sekai", version = "0.1.0" }
jikan = { path = "../jikan", version = "0.1.0" }
keisan = { path = "../keisan", version = "0.1.0" }
daikoku = { path = "../daikoku", version = "0.1.0" }
butsuri = { path = "../butsuri", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
bincode = "1"

[lib]
path = "src/lib.rs"
